server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HospitalManagementDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database: mysql
    database-platform: MYSQL

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: HospitalManagementDB

  devtools:
    livereload:
      enabled: true
    add-properties: true